### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by bangdrie** [Altcoin-Master/Bitfishcoin#1]
error when trying to compile the file
fatal error: bls-dash/bls.hpp: No such file or directory
how to fix this ?

**Comment by Altcoin-Master** [comment]
cd depends
make HOST=x86_64-pc-linux-gnu

**Comment by Altcoin-Master** [comment]
https://github.com/Altcoin-Master/Bitfishcoin/releases/download/v1.1.0.0/bitfishcoin-ubuntu18-1.1.0.0.zip
