### ISSUE TITLE
not working on ubuntu 18.04

### ISSUE THREAD

**Issue by nitrocon** [Altcoin-Master/Bitfishcoin#2]
hi, the precompiled needs some libs, ubuntu 18 does not have them nor can I install them

./bitfishcoind: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./bitfishcoind)

**Comment by Altcoin-Master** [comment]
cd depends
make HOST=x86_64-pc-linux-gnu

**Comment by Altcoin-Master** [comment]
https://github.com/Altcoin-Master/Bitfishcoin/releases/download/v1.1.0.0/bitfishcoin-ubuntu18-1.1.0.0.zip
